### ISSUE TITLE
Sim crashes in phet-io brand, Assertion failed: Stateful PhET-iO Properties must specify a phetioValueType: 

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#183]
Stack:

```
assert.js:28 Uncaught Error: Assertion failed: Stateful PhET-iO Properties must specify a phetioValueType: centerAndVariability.variabilityScreen.model.selectedSceneModelProperty
    at window.assertions.assertFunction (assert.js:28:13)
    at new ReadOnlyProperty (ReadOnlyProperty.ts:206:19)
    at new Property (Property.ts:17:5)
    at new CAVModel (CAVModel.ts:49:39)
    at new VariabilityModel (VariabilityModel.ts:47:5)
    at VariabilityScreen.createModel (VariabilityScreen.ts:37:13)
    at VariabilityScreen.initializeModel (Screen.ts:295:24)
    at Array.<anonymous> (Sim.ts:883:16)
    at Sim.ts:894:25
```

**Comment by samreid** [comment]
This is blocking https://github.com/phetsims/center-and-variability/issues/82 getting finished

**Comment by samreid** [comment]
Fixed, closing.
