### ISSUE TITLE
Failure when kicking in the state wrapper: Assertion failed:  stateObject is not valid for x

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-variability#202]
```
Assertion failed:  stateObject is not valid for x
assert.js:28 Uncaught Error: Assertion failed: stateObject is not valid for x
    at window.assertions.assertFunction (assert.js:28:13)
    at StateSchema.ts:147:35
    at Array.forEach (<anonymous>)
    at StateSchema.checkStateObjectValid (StateSchema.ts:140:29)
    at IOType.isStateObjectValid (IOType.ts:403:43)
    at IOType.validateStateObject (IOType.ts:436:10)
    at IOType.toStateObject (IOType.ts:281:24)
    at Object.getData (ReadOnlyProperty.ts:306:35)
    at Vector2Property.phetioStartEvent (PhetioObject.ts:467:46)
    at Vector2Property._notifyListeners (ReadOnlyProperty.ts:301:67)
```

It looks like `reorganizeStack` is being called in the downstream sim, then a Vector2 is ending up with: `x: null, y: 0.3`

**Comment by samreid** [comment]
This commit seems to fix the problem, but I don't really understand why it was happening in the first place.  Can we review and investigate?

**Comment by marlitas** [comment]
We pushed what we believe to be a fix above. We think that the phaseProperty and the valueProperty need to be tied together as dependencies in state. We will keep an eye on CT to see if the null assertion error comes back, otherwise this will be ready to close.

**Comment by samreid** [comment]
@marlitas and I both hit errors while working on #426, and we added the commit above and it seems to help. We will see how CT does.

**Comment by samreid** [comment]
No phet-io-state-related errors in the last 30 columns of CT. Closing.
