### ISSUE TITLE
CT max should be the same as the scene model

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#239]
```
center-and-variability : interactive-description-fuzz-fuzzBoard-combo : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1685741954493%22%2C%22timestamp%22%3A1685742970271%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
Uncaught Error: Assertion failed: max should be the same as the scene model
Error: Assertion failed: max should be the same as the scene model
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/assert/js/assert.js:28:13)
at assert (IQRNode.ts:241:20)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
at emit (VariabilitySceneModel.ts:134:49)
at updateDataMeasures (CAVSceneModel.ts:129:42)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:316:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1685741954493%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26ea%26supportsInteractiveDescription%3Dtrue%26fuzz%26fuzzBoard&duration=40000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1685741954493%22%2C%22timestamp%22%3A1685742970271%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1685741954493%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26ea%26supportsInteractiveDescription%3Dtrue%26fuzz%26fuzzBoard&duration=40000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1685741954493%22%2C%22timestamp%22%3A1685742970271%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1685741954493%22%2C%22timestamp%22%3A1685742970271%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: max should be the same as the scene model
[PAGE ERROR] Error: Error: Assertion failed: max should be the same as the scene model
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/assert/js/assert.js:28:13)
at updateIQRNode (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/center-and-variability/js/variability/view/IQRNode.js:195:21)
at TinyEmitter.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at Emitter.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/axon/js/Emitter.js:50:22)
at VariabilitySceneModel.updateDataMeasures (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/center-and-variability/js/variability/model/VariabilitySceneModel.js:103:50)
at updateDataMeasures (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/center-and-variability/js/common/model/CAVSceneModel.js:90:43)
at TinyProperty.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at EnumerationProperty._notifyListeners (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/axon/js/ReadOnlyProperty.js:240:23)
at EnumerationProperty.unguardedSet (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/axon/js/ReadOnlyProperty.js:189:14)
at EnumerationProperty.set (http://127.0.0.1/continuous-testing/ct-snapshots/1685741954493/chipper/dist/js/axon/js/ReadOnlyProperty.js:174:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 6/2/2023, 3:39:14 PM
```

**Comment by marlitas** [comment]
Work for this CT error has been happening here: https://github.com/phetsims/center-and-variability/issues/240
Closing.
