### ISSUE TITLE
CT Number must be within rangeProperty value

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#248]
```
center-and-variability : fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686015399981%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[1]: Number must be within rangeProperty value.: value failed isValidValue: -8.881784197001252e-16
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/assert/js/assert.js:28:13)
at assert (validate.ts:26:16)
at validate (ReadOnlyProperty.ts:297:14)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:54:10)
at (IntervalToolPlayAreaNode.ts:101:40)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:316:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
id: Sparky Puppeteer
Snapshot from 6/5/2023, 6:18:13 PM

----------------------------------

center-and-variability : fuzz : unbuilt : assertSlow
http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686019059199%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Uncaught Error: Assertion failed: Trail visibility failure
Error: Assertion failed: Trail visibility failure
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/assert/js/assert.js:28:13)
at assertSlow (Instance.js:1888:6)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686010693682%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686019059199%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686010693682%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686019059199%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686019059199%7D&brand=phet&eall&fuzz
[CONSOLE] enabling assert
[CONSOLE] enabling assertSlow
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: Trail visibility failure
[PAGE ERROR] Error: Error: Assertion failed: Trail visibility failure
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/assert/js/assert.js:28:13)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1686:7)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 6/5/2023, 6:18:13 PM

----------------------------------

center-and-variability : fuzz : unbuilt : assertSlow
http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686032208828%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Uncaught Error: Assertion failed: Trail visibility failure
Error: Assertion failed: Trail visibility failure
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/assert/js/assert.js:28:13)
at assertSlow (Instance.js:1888:6)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686010693682%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686032208828%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1686010693682%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686032208828%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686032208828%7D&brand=phet&eall&fuzz
[CONSOLE] enabling assert
[CONSOLE] enabling assertSlow
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: Trail visibility failure
[PAGE ERROR] Error: Error: Assertion failed: Trail visibility failure
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/assert/js/assert.js:28:13)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1686:7)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
at Instance.auditVisibility (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/chipper/dist/js/scenery/js/display/Instance.js:1693:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 6/5/2023, 6:18:13 PM

----------------------------------

center-and-variability : fuzz : unbuilt : assertSlow
http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686040845003%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Uncaught Error: Assertion failed: Trail visibility failure
Error: Assertion failed: Trail visibility failure
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/assert/js/assert.js:28:13)
at assertSlow (Instance.js:1888:6)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
at auditVisibility (Instance.js:1898:22)
id: Sparky Puppeteer
Snapshot from 6/5/2023, 6:18:13 PM

----------------------------------

center-and-variability : interactive-description-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1686010693682%22%2C%22timestamp%22%3A1686019673010%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[1]: Number must be within rangeProperty value.: value failed isValidValue: -8.881784197001252e-16
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1686010693682/assert/js/assert.js:28:13)
at assert (validate.ts:26:16)
at validate (ReadOnlyProperty.ts:297:14)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:54:10)
at (IntervalToolPlayAreaNode.ts:101:40)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:316:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
id: Sparky Puppeteer
Snapshot from 6/5/2023, 6:18:13 PM
```

**Comment by marlitas** [comment]
This was caused by a rounding error. We were able to fix in the above commit. Closing as completed.
