### ISSUE TITLE
Dragging a card in the state wrapper causes 'Uncaught TypeError: Cannot read properties of undefined (reading 'animateTo')'

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/center-and-variability#337]
To reproduce:
- Open CaV screen 1 in studio
- Kick some soccer balls
- Hit 'Test'
- Try to drag a card

The console will read:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'animateTo')
    at CardNodeContainer.animateToHomeCell (CardNodeContainer.ts:684:14)
    at CardNodeContainer.ts:513:16
    at TinyProperty.emit (TinyEmitter.ts:122:9)
    at Vector2Property._notifyListeners (ReadOnlyProperty.ts:315:23)
    at Vector2Property.unguardedSet (ReadOnlyProperty.ts:262:14)
    at Vector2Property.set (ReadOnlyProperty.ts:246:12)
    at set value [as value] (Property.ts:54:11)
    at DragListener.reposition (DragListener.ts:687:35)
    at DragListener.ts:349:12
    at DragListener.onPress (PressListener.ts:729:17)

**Comment by marlitas** [comment]
I believe this issue was also addressed by commits in: https://github.com/phetsims/center-and-variability/issues/347

Will include as part of that review.

**Comment by matthew-blackman** [comment]
Tested from a few different states and this issue is no longer occurring. Will review as part of #347, but closing this unless the error reappears.
