### ISSUE TITLE
CT The intervalToolValue2Property is outside of it's range:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#362]
```
center-and-variability : multitouch-fuzz : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1689341284408%22%2C%22timestamp%22%3A1689342180626%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Uncaught Error: Assertion failed: The intervalToolValue2Property is outside of it's range: 19.622950819672116
Error: Assertion failed: The intervalToolValue2Property is outside of it's range: 19.622950819672116
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/assert/js/assert.js:28:13)
at assert (IntervalToolNode.ts:132:18)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (DynamicProperty.ts:310:10)
at set (DynamicProperty.ts:328:9)
at (DragListener.ts:687:34)
at reposition (DragListener.ts:292:15)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1689341284408%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dfalse&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1689341284408%22%2C%22timestamp%22%3A1689342180626%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1689341284408%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dfalse&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1689341284408%22%2C%22timestamp%22%3A1689342180626%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1689341284408%22%2C%22timestamp%22%3A1689342180626%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: The intervalToolValue2Property is outside of it's range: 19.622950819672116
[PAGE ERROR] Error: Error: Assertion failed: The intervalToolValue2Property is outside of it's range: 19.622950819672116
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/assert/js/assert.js:28:13)
at http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/center-and-variability/js/variability/view/IntervalToolNode.js:103:19
at TinyProperty.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at DynamicProperty._notifyListeners (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at DynamicProperty.unguardedSet (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DynamicProperty.set (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/axon/js/DynamicProperty.js:252:11)
at set value [as value] (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/axon/js/DynamicProperty.js:269:10)
at DragListener.reposition (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172//continuous-testing/ct-snapshots/1689341284408/chipper/dist/js/scenery/js/listeners/DragListener.js:163:16)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 7/14/2023, 7:28:04 AM
```

**Comment by marlitas** [comment]
I fuzzed for 5 minutes on my machine and could not replicate. I also did not see this coming up on CT within the last 24 hours. Perhaps this got fixed through a separate issue? Closing, and please re-open if it appears again.
