### ISSUE TITLE
CT: There are no data points to return values for. 

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#368]
Coming up on CT:

```
center-and-variability : phet-io-state-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1689702260640/phet-io-wrappers/state/?sim=center-and-variability&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1689702260640%22%2C%22timestamp%22%3A1689702530439%7D
Error: Assertion failed: There are no data points to return values for.
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1689702260640/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1689702260640/assert/js/assert.js:28:13)
at assert (SoccerSceneModel.ts:303:14)
at getDataValues (MeanAndMedianInfoNode.ts:41:34)
at (TinyEmitter.ts:122:18)
at emit (Emitter.ts:61:21)
at emit (SoccerSceneModel.ts:194:36)
at (TinyEmitter.ts:122:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:363:46)
at listener (PropertyStateHandler.ts:281:40)
at attemptToApplyPhases (PropertyStateHandler.ts:201:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:96:11)
at (TinyEmitter.ts:122:18)
at emit (Emitter.ts:61:21)
at emit (PhetioStateEngine.ts:273:25)
at setState (PhetioStateEngine.ts:284:9)
at setFullState (phetioEngine.ts:1063:64)
at apply (phetioCommandProcessor.ts:420:50)
at processCommand (phetioCommandProcessor.ts:298:35)
at getReturn (phetioCommandProcessor.ts:302:15)
at map (phetioCommandProcessor.ts:296:29)
at processCommands (phetioCommandProcessor.ts:238:15)
at addEventListener (phetioCommandProcessor.ts:193:11)
at (phetioCommandProcessor.ts:536:31)
id: Sparky Playwright Firefox
Snapshot from 7/18/2023, 1:44:20 PM
```

**Comment by samreid** [comment]
It looks like there is a discrepancy in the guards. At the call site of the error, it says:

```ts
    sceneModel.objectChangedEmitter.addListener( () => {
      if ( hasEnoughDataProperty.value ) {
        const values = sceneModel.getDataValues();
        const denominator = values.length;
```

However, the assertion in `getDataValues` is:

```ts
  public getDataValues(): number[] {
    const sortedObjects = this.getSortedStackedObjects();

    assert && assert( sortedObjects.length > 0, 'There are no data points to return values for.' );
    return sortedObjects.map( soccerBall => soccerBall.valueProperty.value! );
  }
```

So while the state set values are resolving, perhaps the `hasEnoughDataProperty` becomes true before the sortedStackedObjects array has been filled in.  If this hypothesis is true, then perhaps we would just ignore the bad intermediate value?  Or we could try to unify these predicates--perhaps like this?

```diff

Subject: [PATCH] Remove VariabilityModel.meanAbsoluteDeviation and its usages (including unit tests and unit test harness), see https://github.com/phetsims/center-and-variability/issues/371
---
Index: js/mean-and-median/view/MeanAndMedianInfoNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/mean-and-median/view/MeanAndMedianInfoNode.ts b/js/mean-and-median/view/MeanAndMedianInfoNode.ts
--- a/js/mean-and-median/view/MeanAndMedianInfoNode.ts	(revision a1f163887add5d28241329e95903d266b146c499)
+++ b/js/mean-and-median/view/MeanAndMedianInfoNode.ts	(date 1689829808308)
@@ -38,7 +38,14 @@
     const resultDenominatorText = new Text( '', { fontSize: CAVConstants.INFO_DIALOG_FONT_SIZE, maxWidth: CAVConstants.INFO_DIALOG_MAX_TEXT_WIDTH } );
 
     sceneModel.objectChangedEmitter.addListener( () => {
-      if ( hasEnoughDataProperty.value ) {
+
+      const a = sceneModel.getSortedStackedObjects().length > 0;
+      const b = hasEnoughDataProperty.value;
+
+      if ( a !== b ) {
+        console.log( 'a', a, 'b', b );
+      }
+      if ( sceneModel.getSortedStackedObjects().length > 0 ) {
         const values = sceneModel.getDataValues();
         const denominator = values.length;
 
```

In testing, that appears to solve the problem.  @marlitas wrote that assertion, so may be a good reviewer. Commit (without the console.logs) if that seems good to you.

**Comment by marlitas** [comment]
This patch looks good to me. Tested fuzz in state wrapper for a few minutes with no errors. Committed and closing.
