### ISSUE TITLE
CT min should be the same as the scene model

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#421]
```
center-and-variability : phet-io-state-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1690880437306/phet-io-wrappers/state/?sim=center-and-variability&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1690880437306%22%2C%22timestamp%22%3A1690893448899%7D
Uncaught Error: Assertion failed: min should be the same as the scene model
Error: Assertion failed: min should be the same as the scene model
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1690880437306/assert/js/assert.js:28:13)
at assert (IQRNode.ts:271:20)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:363:46)
at listener (PropertyStateHandler.ts:281:40)
at attemptToApplyPhases (PropertyStateHandler.ts:201:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:96:11)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
id: Sparky Puppeteer
Snapshot from 8/1/2023, 3:00:37 AM
```

**Comment by samreid** [comment]
@matthew-blackman and I added 2 commits above, being more graceful about intermediate states during phet-io state setting. Closing.
