### ISSUE TITLE
Variability screen requires exactly 4 instances of VariabilitySceneModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/center-and-variability#545]
Related to #527 ... To test whether the number of scenes is responsible for a delay in opening the Variability screen, I (very reasonably, I think) attempted to reduce the number of scenes by commenting out one of the `VariabilitySceneModel`  instances in VariabilityMode.ts.  For example:

```diff
    const sceneModels = [
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker1Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 3, 5, 10, 10, 25, 32, 45, 65, 45, 32, 25, 10, 10, 5, 3 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker2Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'right' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker3Model' ) ),
-     new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker4Model' ) )
    ];
```

Ideally I wanted to comment out all but 1 instance of VariabilitySceneModel, to compare performance with the other screens that have only 1 scene.  But no matter which instance of `VariabilitySceneModel` I comment out, the sim fails at startup with:

```
CAVPlotNode.ts:74 Uncaught TypeError: Cannot read properties of undefined (reading 'meanValueProperty')
    at new CAVPlotNode (CAVPlotNode.ts:74:18)
    at new RangeNode (RangeNode.ts:40:5)
    at Object.createNode (VariabilityPlotNode.ts:36:29)
    at GroupItemOptions.ts:33:17
    at Array.map (<anonymous>)
    at getGroupItemNodes (GroupItemOptions.ts:28:16)
    at new ToggleNode (ToggleNode.ts:43:19)
    at new VariabilityPlotNode (VariabilityPlotNode.ts:35:24)
    at Object.createNode (VariabilityAccordionBox.ts:71:18)
    at GroupItemOptions.ts:33:17
```

So something in the implementation must be dependent on there being 4 instances of VariabilitySceneModel.  This is not good -- and the fact that it's impeding investigation of #527 is an example of why it's not good.   Highly recommended to identify and remove this dependency.

**Comment by pixelzoom** [comment]
Since I can't remove a `VariabilitySceneModel`, I figured I could investigate #527 by adding instances of `VariabilitySceneModel`, to see if the delay increased.  So I tried:

```diff
    const sceneModels = [
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker1Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 3, 5, 10, 10, 25, 32, 45, 65, 45, 32, 25, 10, 10, 5, 3 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker2Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'right' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker3Model' ) ),
-     new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker4Model' ) )
+      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker4Model' ) ),
+      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker5Model' ) )
    ];
```

Again this fails at startup, with a different error:

```
KickerNode.ts:42 Uncaught TypeError: Cannot read properties of undefined (reading 'standing')
    at new KickerNode (KickerNode.ts:42:72)
    at SoccerSceneView.ts:190:7
    at Array.map (<anonymous>)
    at new SoccerSceneView (SoccerSceneView.ts:189:44)
    at new CAVSceneView (CAVSceneView.ts:35:5)
    at CAVScreenView.ts:166:71
    at Array.map (<anonymous>)
    at new CAVScreenView (CAVScreenView.ts:166:41)
    at new VariabilityScreenView (VariabilityScreenView.ts:67:5)
    at VariabilityScreen.createView (VariabilityScreen.ts:43:38)
```

So this sim is dependent on having exactly 4 instances of `VariabilitySceneModel`.

**Comment by pixelzoom** [comment]
If you don't have time to address this, then at least add an assertion in VariabilityModel for the next person who has to jump in on this sim:

```diff
    const sceneModels = [
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker1Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 3, 5, 10, 10, 25, 32, 45, 65, 45, 32, 25, 10, 10, 5, 3 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker2Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'right' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker3Model' ) ),
     new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker4Model' ) )
    ];
+   assert && assert( sceneModels.length === 4, 'See https://github.com/phetsims/center-and-variability/issues/545' );
```

**Comment by pixelzoom** [comment]
Here's an example of one really awful dependency in VariabilityAccordionBox, where `4` is hardcoded.

```ts
    const contents = _.range( 4 ).map( i => {
      return {
        value: model.sceneModels[ i ],
        createNode: () => {
          return new VariabilityPlotNode( model, model.variabilitySceneModels[ i ], playAreaNumberLineNode, model.isDataPointLayerVisibleProperty, intervalToolNode, {
            bottom: backgroundShape.bounds.height
          } );
        }
      };
    } );
```

Why not `_.range( model.sceneModels.length )`?

**Comment by pixelzoom** [comment]
Tandem names in VariabilityModel is also number and order dependent.  If you change the order of scenes, the tandem names are wrong:

```ts
    const sceneModels = [
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker1Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 3, 5, 10, 10, 25, 32, 45, 65, 45, 32, 25, 10, 10, 5, 3 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker2Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'right' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker3Model' ) ),
     new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker4Model' ) )
    ];
```

The robust way to do this is:

```ts
    const tandemIndex = 1;
    const sceneModels = [
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( `sceneKicker${tandemIndex++}Model` ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 3, 5, 10, 10, 25, 32, 45, 65, 45, 32, 25, 10, 10, 5, 3 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicke${tandemIndex++}Model' ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'right' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker${tandemIndex++}Model' ) ),
-     new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker${tandemIndex++}Model' ) )
    ];
```

**Comment by pixelzoom** [comment]
Another hardcoded dependency in SceneKickerRadioButtonGroup.  I'm finding these as I'm trying to slog my way through reducing the number of scenes to 1.

```ts
    super( property, [ {
      value: sceneModels[ 0 ],
      createNode: tandem => createTShirtIcon( '1', '#7bb772' ),
      tandemName: 'kicker1RadioButton'
    }, {
      value: sceneModels[ 1 ],
      createNode: tandem => createTShirtIcon( '2', '#4f61b4' ),
      tandemName: 'kicker2RadioButton'
    }, {
      value: sceneModels[ 2 ],
      createNode: tandem => createTShirtIcon( '3', '#c15156' ),
      tandemName: 'kicker3RadioButton'
    }, {
      value: sceneModels[ 3 ],
      createNode: tandem => createTShirtIcon( '4', '#eeda63' ),
      tandemName: 'kicker4RadioButton'
    } ], options );
```

**Comment by pixelzoom** [comment]
Here's a patch where I was finally able to reduce the number of VariableSceneModel instances.  It doesn't identify (or even address) all of the dependencies on "exactly 4" scenes, but it's a start.

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] fix faulty assertions, https://github.com/phetsims/function-builder/issues/159
---
Index: js/variability/model/VariabilityModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/variability/model/VariabilityModel.ts b/js/variability/model/VariabilityModel.ts
--- a/js/variability/model/VariabilityModel.ts	(revision ac3bb09703a7ded09d6d15c5a2861113100c220d)
+++ b/js/variability/model/VariabilityModel.ts	(date 1694205064581)
@@ -77,10 +77,7 @@
   public constructor( preferencesModel: SoccerCommonPreferencesModel, providedOptions: VariabilityModelOptions ) {
 
     const sceneModels = [
-      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker1Model' ) ),
-      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 3, 5, 10, 10, 25, 32, 45, 65, 45, 32, 25, 10, 10, 5, 3 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker2Model' ) ),
-      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'right' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker3Model' ) ),
-      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'skew', values: null, skewType: 'left' }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker4Model' ) )
+      new VariabilitySceneModel( MAX_KICKS_PROPERTY, { type: 'probabilityByDistance', values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ], skewType: null }, preferencesModel.kickerCharacterSetProperty, providedOptions.tandem.createTandem( 'sceneKicker1Model' ) )
     ];
 
     const accordionBoxTandem = providedOptions.tandem.createTandem( 'variabilityMeasureAccordionBox' );
Index: js/variability/view/VariabilityAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/variability/view/VariabilityAccordionBox.ts b/js/variability/view/VariabilityAccordionBox.ts
--- a/js/variability/view/VariabilityAccordionBox.ts	(revision ac3bb09703a7ded09d6d15c5a2861113100c220d)
+++ b/js/variability/view/VariabilityAccordionBox.ts	(date 1694205199807)
@@ -64,7 +64,7 @@
         tandem: tandem.createTandem( 'intervalToolNode' )
       } );
 
-    const contents = _.range( 4 ).map( i => {
+    const contents = _.range( model.sceneModels.length ).map( i => {
       return {
         value: model.sceneModels[ i ],
         createNode: () => {
Index: js/variability/view/SceneKickerRadioButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/variability/view/SceneKickerRadioButtonGroup.ts b/js/variability/view/SceneKickerRadioButtonGroup.ts
--- a/js/variability/view/SceneKickerRadioButtonGroup.ts	(revision ac3bb09703a7ded09d6d15c5a2861113100c220d)
+++ b/js/variability/view/SceneKickerRadioButtonGroup.ts	(date 1694205594204)
@@ -58,18 +58,6 @@
       value: sceneModels[ 0 ],
       createNode: tandem => createTShirtIcon( '1', '#7bb772' ),
       tandemName: 'kicker1RadioButton'
-    }, {
-      value: sceneModels[ 1 ],
-      createNode: tandem => createTShirtIcon( '2', '#4f61b4' ),
-      tandemName: 'kicker2RadioButton'
-    }, {
-      value: sceneModels[ 2 ],
-      createNode: tandem => createTShirtIcon( '3', '#c15156' ),
-      tandemName: 'kicker3RadioButton'
-    }, {
-      value: sceneModels[ 3 ],
-      createNode: tandem => createTShirtIcon( '4', '#eeda63' ),
-      tandemName: 'kicker4RadioButton'
     } ], options );
   }
 }
```

</details>

**Comment by marlitas** [comment]
Yes this should definitely get addressed. Thanks for bringing this to the forefront. I'll work on removing these dependencies that should not exist.

**Comment by marlitas** [comment]
I played with the sim a bit and was able to easily reduce down to one scene by commenting out scenes in the `VariabilityModel`. This seems to be working well now and I did not run into any other hardcoded errors. 

Over to @pixelzoom for code review.

**Comment by pixelzoom** [comment]
Tandem name numbering is still hardcoded. See the problem and solution in  https://github.com/phetsims/center-and-variability/issues/545#issuecomment-1712194163.

**Comment by marlitas** [comment]
Ah yes thank you. Missed that one. Commit pushed.

**Comment by pixelzoom** [comment]
Commits above look good.  But there's still a problem.  If I comment out scenes 2 & 3 in VariablilityModel, like this:

```ts
    let sceneTandemIndex = 1;
    // If a new variability scene model is added, a new color associated with that model needs to be added in CAVConstants as well.
    const sceneModels = [
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, {
        type: 'probabilityByDistance',
        values: [ 0, 0, 0, 1, 3, 12, 20, 32, 20, 12, 3, 1, 0, 0, 0 ],
        skewType: null
      }, preferencesModel.kickerCharacterSetProperty, CAVConstants.VARIABILITY_KICKER_COLORS[ 0 ], providedOptions.tandem.createTandem( `sceneKicker${sceneTandemIndex++}Model` ) ),
      // new VariabilitySceneModel( MAX_KICKS_PROPERTY, {
      //   type: 'probabilityByDistance',
      //   values: [ 3, 5, 10, 10, 25, 32, 45, 65, 45, 32, 25, 10, 10, 5, 3 ],
      //   skewType: null
      // }, preferencesModel.kickerCharacterSetProperty, CAVConstants.VARIABILITY_KICKER_COLORS[ 1 ], providedOptions.tandem.createTandem( `sceneKicker${sceneTandemIndex++}Model` ) ),
      // new VariabilitySceneModel( MAX_KICKS_PROPERTY, {
      //   type: 'skew',
      //   values: null,
      //   skewType: 'right'
      // }, preferencesModel.kickerCharacterSetProperty, CAVConstants.VARIABILITY_KICKER_COLORS[ 2 ], providedOptions.tandem.createTandem( `sceneKicker${sceneTandemIndex++}Model` ) ),
      new VariabilitySceneModel( MAX_KICKS_PROPERTY, {
        type: 'skew',
        values: null,
        skewType: 'left'
      }, preferencesModel.kickerCharacterSetProperty, CAVConstants.VARIABILITY_KICKER_COLORS[ 3 ], providedOptions.tandem.createTandem( `sceneKicker${sceneTandemIndex++}Model` ) )
    ];
```

... then I would expect to see radio buttons for jersies 1 & 4.  Instead I see radio buttons 1 & 2:

<img width="233" alt="screenshot_2768" src="https://github.com/phetsims/center-and-variability/assets/3046552/eaf0534f-45a4-4036-878a-89d7b2c13b88">

So you probably need to add the jersey icon for VariabilitySceneModel.

**Comment by pixelzoom** [comment]
Oh, nevermind -- my bad.  This is working correctly because sceneKicker4Model becomes sceneKicker2Model due to https://github.com/phetsims/center-and-variability/commit/2b9ac349bacb21f8887ada1384021e50c3c96348.

Nice work, closing.
