### ISSUE TITLE
CT: IntervalToolValue2Property outside of it's range

### ISSUE THREAD

**Issue by marlitas** [phetsims/center-and-variability#556]
Stack trace from CT:
```
center-and-variability : pan-and-zoom-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695425173878%22%2C%22timestamp%22%3A1695426001422%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught Error: Assertion failed: The intervalToolValue2Property is outside of its range: -5.346017423345045
Error: Assertion failed: The intervalToolValue2Property is outside of its range: -5.346017423345045
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at assert (IntervalToolRectangle.ts:132:18)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (DynamicProperty.ts:232:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695425173878%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695425173878%22%2C%22timestamp%22%3A1695426001422%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695425173878%2Fcenter-and-variability%2Fcenter-and-variability_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695425173878%22%2C%22timestamp%22%3A1695426001422%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/center-and-variability/center-and-variability_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695425173878%22%2C%22timestamp%22%3A1695426001422%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: The intervalToolValue2Property is outside of its range: -5.346017423345045
[PAGE ERROR] Error: Error: Assertion failed: The intervalToolValue2Property is outside of its range: -5.346017423345045
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/center-and-variability/js/variability/view/IntervalToolRectangle.js:100:19
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DynamicProperty.onPropertyPropertyChange (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:181:11)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(252.36218773146265, 434), oldValue=Vector2(130.36218773146265, 56)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(252.36218773146265, 434), oldValue=Vector2(130.36218773146265, 56)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/Property.js:48:11)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:163:16)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
at DragListener.pointerMove (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/PressListener.js:681:14)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(5.346017423345045, 0), oldValue=Vector2(0, 0)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(5.346017423345045, 0), oldValue=Vector2(0, 0)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:252:11)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:269:10)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:163:16)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=5.346017423345045, oldValue=0
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=5.346017423345045, oldValue=0
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/Property.js:48:11)
at DynamicProperty.onSelfChange (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:219:29)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(5.346017423345045, 0), oldValue=Vector2(5.346017423345045, 0)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(5.346017423345045, 0), oldValue=Vector2(5.346017423345045, 0)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:252:11)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:269:10)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:216:12
at DragListener.onPress (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/PressListener.js:528:17)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(5.346017423345045, 0), oldValue=Vector2(5.346017423345045, 0)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(5.346017423345045, 0), oldValue=Vector2(5.346017423345045, 0)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:252:11)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:269:10)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:163:16)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(16, 0), oldValue=Vector2(5.346017423345045, 0)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(16, 0), oldValue=Vector2(5.346017423345045, 0)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:252:11)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:269:10)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:163:16)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(16, 0), oldValue=Vector2(16, 0)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(16, 0), oldValue=Vector2(16, 0)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/assert/js/assert.js:28:13)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:237:15)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:188:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/ReadOnlyProperty.js:173:12)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:252:11)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/axon/js/DynamicProperty.js:269:10)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/DragListener.js:216:12
at DragListener.onPress (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/scenery/js/listeners/PressListener.js:528:17)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1695425173878/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
[CONSOLE] continuous-test-error
```

**Comment by marlitas** [comment]
I added more assertion information and you can see that there's a mismatch in the distanceBetweenValues calculation and `value2 - value1`.

```
Assertion failed:  The intervalToolValue2Property is outside of its range: -8.099109020069239. Calculation that got us here is: (value2) 0 - (value1) 6.09347937954863 = (distanceBetweenValues) -14.19258839961787, The x value of intervalTool handle 1: Vector2(6.09347937954863, 0)
```

I'm going to try and calculate distance between values closer to when it's needed rather at the start of the drag listener. I think there's some outdated data happening there.

**Comment by marlitas** [comment]
I committed a proposed fix. Will keep an eye out for it on CT, otherwise will send over for review.

**Comment by marlitas** [comment]
This error has not showed up on CT since the fix was applied. Sending over to @samreid or @matthew-blackman for review.

**Comment by marlitas** [comment]
There was a bug that popped up from the commits in this issue that were found in https://github.com/phetsims/center-and-variability/issues/560. Closing this issue, and sending review over there.

**Comment by marlitas** [comment]
We are still seeing this issue:

<img width="591" alt="image" src="https://github.com/phetsims/center-and-variability/assets/42476338/288f087f-5d1e-4737-a08a-50c075e87be6">

**Comment by marlitas** [comment]
I think this was fixed with the `&&` vs. `||` bug I found yesterday. I'm not seeing it on CT and after an hour of fuzzing on the third screen it has not come up again. Closing!
