### ISSUE TITLE
Assertion failed: The valueProperty of the selectedGroupItem should not be null.

### ISSUE THREAD

**Issue by zepumph** [phetsims/center-and-variability#606]
```
center-and-variability : migration : 1.1->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/phet-io-wrappers/migration/?sim=center-and-variability&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D
Uncaught Error: Assertion failed: The valueProperty of the selectedGroupItem should not be null.
Error: Assertion failed: The valueProperty of the selectedGroupItem should not be null.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/assert/js/assert.js:28:13)
at assert (SoccerCommonGroupSortInteractionView.ts:160:20)
at listener (TinyEmitter.ts:123:8)
at emit (Emitter.ts:62:21)
at emit (SoccerSceneModel.ts:243:35)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:328:22)
at _notifyListeners (ReadOnlyProperty.ts:376:46)
at listener (PropertyStateHandler.ts:273:40)
at attemptToApplyPhases (PropertyStateHandler.ts:193:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1705489115936%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dcenter-and-variability%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1705489115936%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dcenter-and-variability%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/phet-io-wrappers/migration/?sim=center-and-variability&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D
[ATTACHED]
[NAVIGATED] about:blank
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/studio/?sim=center-and-variability&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D&phetioMigrationReport=assert&fuzz&locales=*
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/center-and-variability/center-and-variability_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=center-and-variability&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found): http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/soccer-common/soccer-common-strings_en.json
[NAVIGATED] https://phet-io.colorado.edu/sims/center-and-variability/1.1/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[CONSOLE] enabling assert
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1705489115936%22%2C%22timestamp%22%3A1705492972884%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: The valueProperty of the selectedGroupItem should not be null.
[PAGE ERROR] Error: Error: Assertion failed: The valueProperty of the selectedGroupItem should not be null.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/soccer-common/js/view/SoccerCommonGroupSortInteractionView.js:114:21
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/Emitter.js:51:22)
at http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/soccer-common/js/model/SoccerSceneModel.js:186:36
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at SoccerBallValueProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/ReadOnlyProperty.js:252:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/ReadOnlyProperty.js:297:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
[PAGE ERROR] Error: Error: Assertion failed: The valueProperty of the selectedGroupItem should not be null.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/soccer-common/js/view/SoccerCommonGroupSortInteractionView.js:114:21
at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/Emitter.js:51:22)
at http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/soccer-common/js/model/SoccerSceneModel.js:186:36
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at SoccerBallValueProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/ReadOnlyProperty.js:252:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/ReadOnlyProperty.js:297:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1705489115936/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 1/17/2024, 3:58:35 AM
```

**Comment by zepumph** [comment]
This will be dealt with over in https://github.com/phetsims/scenery-phet/issues/815.

**Comment by marlitas** [comment]
I believe this has indeed been addressed. I got no migration errors in the migration wrapper, and CT looks clean as well. Closing.
