### ISSUE TITLE
CT  MigrationReport problem: stateSchemaIncompatible

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#618]
```
center-and-variability : migration : 1.1->main : assert
http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/phet-io-wrappers/migration/?sim=center-and-variability&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D
Assertion failed: MigrationReport problem: stateSchemaIncompatible

{
"clientMessages": [
"regionAndCulturePortrayals is no longer supported. See regionAndCultureProperty."
],
"stateSchemaIncompatible": [
{
"phetioID": "centerAndVariability.general.model.regionAndCultureProperty",
"problem": [
"one state schema was a value string and one was composite: migratedStateSchema = ",
{
"phetioID": "StringIO"
},
"newStateSchema = ",
"string",
"validValues",
"full state schema",
{
"units": "NullableIO<StringIO>",
"validValues": "NullableIO<ArrayIO<RegionAndCulturePortrayalIO>>",
"value": "RegionAndCulturePortrayalIO"
}
]
},
{
"phetioID": "centerAndVariability.general.model.regionAndCultureProperty",
"problem": [
"one state schema was a value string and one was composite: migratedStateSchema = ",
{
"phetioID": "StringIO"
},
"newStateSchema = ",
"string",
"value",
"full state schema",
{
"units": "NullableIO<StringIO>",
"validValues": "NullableIO<ArrayIO<RegionAndCulturePortrayalIO>>",
"value": "RegionAndCulturePortrayalIO"
}
]
}
],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [
"centerAndVariability.global.model.preferences.regionAndCulturePortrayals",
"centerAndVariability.global.model.preferences.regionAndCulturePortrayals"
],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/assert/js/assert.js:28:13)
at assert (MigrationReport.ts:164:22)
at reportForContext (MigrationEngine.ts:86:22)
at migrate (StandardPhetioWrapper.ts:281:37)
at loadStandardPhetioWrapperFromHTML (PhetioClient.ts:1483:38)
at onBothStudiosLoaded/< (http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/phet-io-wrappers/migration/migration.js:220:66)
at EventListener.handleEvent*onBothStudiosLoaded (http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/phet-io-wrappers/migration/migration.js:216:12)
at <unknown> (http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/phet-io-wrappers/migration/migration.js:100:11)
at EventListener.handleEvent* (http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/phet-io-wrappers/migration/migration.js:89:10)
at async* (http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/phet-io-wrappers/migration/migration.js:267:4)
[URL] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1710813640254%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dcenter-and-variability%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1710813640254%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dcenter-and-variability%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/phet-io-wrappers/migration/?sim=center-and-variability&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D
[ATTACHED]
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/studio/?sim=center-and-variability&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&locales=*
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/center-and-variability/center-and-variability_en.html?brand=phet-io&ea&postMessageOnError&sim=center-and-variability&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/center-and-variability/1.1/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[CONSOLE] enabling assert
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "https://phet-io.colorado.edu/sims/center-and-variability/1.1/center-and-variability_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22center-and-variability%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1710813640254%22%2C%22timestamp%22%3A1710814164276%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 18697}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1710813640254/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: MigrationReport problem: stateSchemaIncompatible

{
"clientMessages": [
"regionAndCulturePortrayals is no longer supported. See regionAndCultureProperty."
],
"stateSchemaIncompatible": [
{
"phetioID": "centerAndVariability.general.model.regionAndCultureProperty",
"problem": [
"one state schema was a value string and one was composite: migratedStateSchema = ",
{
"phetioID": "StringIO"
},
"newStateSchema = ",
"string",
"validValues",
"full state schema",
{
"units": "NullableIO<StringIO>",
"validValues": "NullableIO<ArrayIO<RegionAndCulturePortrayalIO>>",
"value": "RegionAndCulturePortrayalIO"
}
]
},
{
"phetioID": "centerAndVariability.general.model.regionAndCultureProperty",
"problem": [
"one state schema was a value string and one was composite: migratedStateSchema = ",
{
"phetioID": "StringIO"
},
"newStateSchema = ",
"string",
"value",
"full state schema",
{
"units": "NullableIO<StringIO>",
"validValues": "NullableIO<ArrayIO<RegionAndCulturePortrayalIO>>",
"value": "RegionAndCulturePortrayalIO"
}
]
}
],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [
"centerAndVariability.global.model.preferences.regionAndCulturePortrayals",
"centerAndVariability.global.model.preferences.regionAndCulturePortrayals"
],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
} JSHandle@object
[CONSOLE] continuous-test-wrapper-error
[PAGE ERROR] Error: Assertion failed: MigrationReport problem: stateSchemaIncompatible

{
"clientMessages": [
"regionAndCulturePortrayals is no longer supported. See regionAndCultureProperty."
],
"stateSchemaIncompatible": [
{
"phetioID": "centerAndVariability.general.model.regionAndCultureProperty",
"problem": [
"one state schema was a value string and one was composite: migratedStateSchema = ",
{
"phetioID": "StringIO"
},
"newStateSchema = ",
"string",
"validValues",
"full state schema",
{
"units": "NullableIO<StringIO>",
"validValues": "NullableIO<ArrayIO<RegionAndCulturePortrayalIO>>",
"value": "RegionAndCulturePortrayalIO"
}
]
},
```

**Comment by samreid** [comment]
CT no longer shows stateSchemaIncompatible, but it has other problems related to https://github.com/phetsims/center-and-variability/issues/615. Let's continue in that issue. Closing.
