### ISSUE TITLE
CT cannot read properties of undefined reading width

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/center-and-variability#97]
```
center-and-spread : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/center-and-spread/center-and-spread_en.html?continuousTest=%7B%22test%22%3A%5B%22center-and-spread%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647574186761%22%2C%22timestamp%22%3A1647577954911%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'width')
TypeError: Cannot read properties of undefined (reading 'width')
at AsyncCounter.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/center-and-spread/js/common/view/CardNodeContainer.js:149:109)
at AsyncCounter.increment (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/center-and-spread/js/common/model/AsyncCounter.js:25:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/center-and-spread/js/common/view/CardNodeContainer.js:191:69
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/axon/js/Emitter.js:47:22)
at Animation.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/twixt/js/Animation.js:287:25)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/joist/js/Sim.js:251:17
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647574186761/chipper/dist/js/joist/js/Sim.js:822:31)
id: Bayes Chrome
Snapshot from 3/17/2022, 9:29:46 PM
```

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/tasks/issues/1106

**Comment by samreid** [comment]
Proposed fix working well locally, let's close and reopen if it recurs.
